spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: 1234
#    spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

springdoc:
  api-docs:
    #  set another path to OpenAPI descriptions, path by default: /v3/api-docs/
    path: /api-docs
  #  set another path to swagger-ui, path by default: /swagger-ui.html
  swagger-ui:
    path: /api/swagger-ui.html
# for sort the API paths in order of their HTTP methods
# springdoc.swagger-ui.operationsSorter=method